### ISSUE TITLE
RenewRepo #2

### ISSUE THREAD

**Issue by qwgsdy** [dl1ycf/pihpsdr#28]
Another attempt also fails.
I am not a LINUX expert. See the attachments.
Please suggest a solution ...
![Screenshot_08](https://github.com/dl1ycf/pihpsdr/assets/150385654/b54af54a-bb19-4b72-b60d-c1d98aa8e529)
![Screenshot_07](https://github.com/dl1ycf/pihpsdr/assets/150385654/59edf931-84d5-4525-a8df-280d206542e8)
![Screenshot_06](https://github.com/dl1ycf/pihpsdr/assets/150385654/51f0e032-e3aa-41ad-8f42-e1bb78ee9798)
![Screenshot_05](https://github.com/dl1ycf/pihpsdr/assets/150385654/e5639a86-90b9-482a-8ad1-1636ce8969bb)

**Comment by CT1IQI** [comment]
To update the local copies of the github repositories you have to give a 'git pull' command from the directory where the local copy is situated. They are under /home/pi/github in 
/home/pi/github/pihpsdr and /home/pi/github/Saturn
But that is not where you are looking, and the error message is crystal clear "Datei nicht gefunden".
So, e.g. to make the latest pihpsdr, do
  cd /home/pi/github/pihpsdr
  git pull
  make clean
  make
You can also put this on one line with && in between the parts which is a logical expression meaning do the following if the previous finished with success.
cd /home/pi/github/pihpsdr && git pull && make clean && make

Confusing in naming is that when all went successful the executable binary will also be called pihpsdr
I normally copy that binary to /usr/local/bin/ directory:
sudo cp /home/pi/github/pihpsdr/pihpsdr /usr/local/bin/

The original OS image does not have a directory /home/pi/pihpsdr. You better remove it after having copied the configuration files it may have to /home/pi/.config/pihpsdr
Looking at the source code of pihpsdr it looks for that directory /home/pi/.config/pihpsdr for its configuration files.
The original OS is not properly configured, has the .config, but not its subdirectory pihpsdr.
You don't see the .config in the GUI because you have not set hidden directories to be shown (the . makes it hidden type)

You can make the directory with 
mkdir -p  /home/pi/.config/pihpsdr
(from the command line you can get loads of help about all commands by typing 'man <command>'; e.g. man mkdir will tell you that the -p option will create intermediate directory levels as needed)

**Comment by qwgsdy** [comment]
MARTINUS, Your posting was very helpful. Thank you

**Comment by dl1ycf** [comment]
The real problem was that the "git  clone" terminated with some obscure error message.
NOTE FOR G2: it seems that your pihpsdr normally resides in /home/Github/pihpsdr not in /home/pihpsdr.
This then leads to two installations this shoudl be avoided. I shall update the PDF.

**Comment by dl1ycf** [comment]
Can this be closed now?

**Comment by qwgsdy** [comment]
Yes, it can closed.
