### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by CS22332615** [dl1ycf/pihpsdr#37]
Not sure if it is possible but in Thetis, you can click on the AGC Slider and enable Auto RF gain which adjusts the RF Gain Attenuation based on the noise floor. In piHPSDR it would be an auto tracking RF gain control to prevent ADC Overload and having to manually adjust the RF Slider. Hermes Lite 2 application. It’s possible too that I’m missing the option in piHPSDR.

**Comment by dd5md** [comment]
I agree that "Auto RF gain" should definitely be integrated into piHPSDR.

In addition, a menu extension for audio "Line-Out" to sound card with selectable audio device such as loopback etc. would be important in order to be able to integrate the audio TX/RX into e.g. screen videos or live streams.

**Comment by dl1ycf** [comment]
First, ADC gain and RF attenuation/gain are different things. ADC gain is done in the data processing, while RF gain/attenuation is a physical device in the RF front end. I think you *mean* ADC gain but this has nothing to do with ADC overload, so your suggestion is a bit ill-defined.

I guess you mean the following but I am not sure:

the ADC gain should be auto-adjusted such that the "green ADC line" sticks to the noise floor. 

Is it this what you have in mind? I won't do that (perhaps there is a volunteer) since in a crowded band / contest operation it might be difficult to automatically determine what is the noise floor.
